[package]
name = "spaad_example_generated"
version = "0.1.0"
authors = ["Restioson <restiosondev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spaad = { path = "../", features = ["with-tokio-0_2", "stable"] }
xtra = { path = "../../xtra" } # TODO 0.3 xtra
tokio = { version = "0.2", features = ["full"] }
async-trait = "0.1"
